INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("apple", "tech", 100, 0406, 0509);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("microsoft", "tech", 10, 0111, 0913);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("airbnb", "hospitality", 93874289347, 0330, 1231);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("facebook", "social media", 8347293, 1219, 0101);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("google", "search", 999393, 1118, 0911);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("twitter", "social media", 39283, 1031, 1111);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("instagram", "social media", 350, 0911, 1212);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("youtube", "video", 292, 0411, 0606);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("flickr", "photography", 485793, 0824, 0909);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("vimeo", "video", 32490, 0505, 0808);

INSERT INTO users (name, age) VALUES ("Sarah", 12);
INSERT INTO users (name, age) VALUES ("Jordan", 35);
INSERT INTO users (name, age) VALUES ("Katy", 19);
INSERT INTO users (name, age) VALUES ("Katie", 25);
INSERT INTO users (name, age) VALUES ("Lauren", 11);
INSERT INTO users (name, age) VALUES ("Mike", 2);
INSERT INTO users (name, age) VALUES ("AJ", 66);
INSERT INTO users (name, age) VALUES ("Brett", 98);
INSERT INTO users (name, age) VALUES ("Amy", 42);
INSERT INTO users (name, age) VALUES ("Jeffrey", 56);
INSERT INTO users (name, age) VALUES ("Rosie", 6);
INSERT INTO users (name, age) VALUES ("Max", 6);
INSERT INTO users (name, age) VALUES ("Sloan", 25);
INSERT INTO users (name, age) VALUES ("Catherine", 26);
INSERT INTO users (name, age) VALUES ("Leah", 24);
INSERT INTO users (name, age) VALUES ("Miranda", 22);
INSERT INTO users (name, age) VALUES ("Zach", 29);
INSERT INTO users (name, age) VALUES ("Jane", 19);
INSERT INTO users (name, age) VALUES ("Carolyn", 89);
INSERT INTO users (name, age) VALUES ("Joanna", 70);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 6, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1100, 3, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1200, 6, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1300, 7, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1400, 4, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500, 10, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1600, 5, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1700, 7, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1800, 4, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1900, 3, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 1, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2100, 2, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2200, 4, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2300, 9, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2400, 6, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2500, 6, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2600, 7, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2700, 3, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2800, 8, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2900, 10, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 9, 11);